---
# tasks file for ansible-role-homebrew
- name: Install Homebrew taps
  homebrew_tap:
    tap: "{{ item.name }}"
    state: present
  loop: "{{ homebrew_taps|flatten(levels=1) }}"

- name: Update Homebrew
  homebrew:
    update_homebrew: yes
  when: homebrew_update == true

- name: Upgrade installed Homebrew packages
  homebrew:
    upgrade_all: yes
  when: homebrew_upgrade == true

- name: Install Homebrew packages
  homebrew:
    name: "{{ item.name }}"
    state: latest
  loop: "{{ homebrew_packages|flatten(levels=1) }}"

- name: Install Homebrew casks
  homebrew_cask:
    name: "{{ item.name }}"
    state: present
  loop: "{{ homebrew_casks|flatten(levels=1) }}"
